export { AcademicYearManagementPage } from './AcademicYearManagementPage';
export { DashboardPage } from './DashboardPage';
export { default as StudentPersonalInfoPage } from './StudentPersonalInfoPage';
export { default as StudentAcademicInfoPage } from './StudentAcademicInfoPage';
export { default as SchoolInfoManagementPage } from './SchoolInfoManagementPage';
export { default as ActivitiesManagementPage } from './ActivitiesManagementPage';
export { default as AddEditGradePage } from './AddEditGradePage';
export { default as TeacherManagementPage } from './TeacherManagementPage';
export { default as DirectorNotesPage } from './DirectorNotesPage';
export { default as DirectorNotesSearchPage } from './DirectorNotesSearchPage';
export { ScheduleManagementPage } from './ScheduleManagementPage';
export { default as UserManagementPage } from './UserManagementPage';
export { default as SettingsPage } from './SettingsPage';
export { default as UpdateTestPage } from './UpdateTestPage';
