# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for DAS Backend
# Using onefile mode for single executable sidecar compatible with Tauri

block_cipher = None

a = Analysis(
    ['run_server.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('app', 'app'),
    ],
    hiddenimports=[
        # FastAPI
        'fastapi',
        'fastapi.applications',
        'fastapi.routing',
        'fastapi.params',
        'fastapi.dependencies',
        'fastapi.security',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.staticfiles',
        'fastapi.responses',
        'fastapi.exceptions',
        # Uvicorn
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        # Starlette
        'starlette.responses',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.staticfiles',
        'starlette.exceptions',
        'starlette.status',
        # Pydantic
        'pydantic',
        'pydantic_core',
        'pydantic.deprecated.decorator',
        # SQLAlchemy & SQLCipher
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.ext.declarative',
        'sqlcipher3',
        # Authentication & Security
        'passlib.context',
        'passlib.handlers',
        'passlib.handlers.bcrypt',
        'passlib.hash',
        'passlib.utils',
        'passlib.utils.compat',
        'passlib.crypto',
        'passlib.crypto.digest',
        'bcrypt',
        '_cffi_backend',
        'jose',
        'jose.jwt',
        'jose.exceptions',
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.ciphers',
        'cryptography.hazmat.backends',
        # Async
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'sniffio',
        'aiohttp',
        'aiohttp.client',
        # File handling
        'PIL',
        'PIL.Image',
        'openpyxl',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'openpyxl.styles',
        'openpyxl.utils',
        'magic',
        # Utilities
        'click',
        'email_validator',
        'python_multipart',
        'multipart',
        'schedule',
        'psutil',
        'slowapi',
        'slowapi.errors',
        'slowapi.util',
        # JWT
        'jwt',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pytest',
        'coverage',
        'setuptools',
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'IPython',
        'notebook',
        'jupyter',
        'app',  # Exclude app from analysis - we include it as data
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    exclude_binaries=False,
    name='school-management-backend-x86_64-pc-windows-msvc',
    debug=False,
    bootloader_ignore_signals=True,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
